## Numpy dizilerini hazır bir şekilde oluşturmak için geliştirdiği methodlar

## !!! arange methodu !!!

In [8]:
import numpy as np

In [9]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,20,2) ##step size(atlayarak gitme)= 2 değeri 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## !!! zeros methodu !!!

In [16]:
np.zeros(5) ##sıfır yazdırmak istediğimizde kullanırız

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

## !!! ones methodu !!!

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## !!! linspace methodu !!!

In [20]:
## belirtilen sayılar arasında istenilen değer kadar eşit aralıklarla bir dizi oluşturulmasını sağlar

In [22]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [23]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## !!! eye !!!

In [25]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
##matrixte ilk satırda ilk stundan(1x1) başlayarak her satırda 1 leri birer stun kaydırarak yazdırmayı sağlar