## Random Kütüphanesi

In [2]:
import numpy as np

In [10]:
np.random.randn(4) ##rastgele değer döndürmek için kullanılır

array([ 1.97527533, -0.08977996, -0.14413989,  0.29090666])

In [11]:
np.random.randn(4,4)

array([[ 0.11439078,  1.60899158,  1.65863293,  0.37371976],
       [ 0.40550905, -1.66402207,  0.65018716, -0.2491272 ],
       [ 0.91368251,  1.80600571, -0.0262764 ,  0.15416589],
       [ 0.45802772, -0.20431532,  1.11750887, -0.67431549]])

In [20]:
np.random.randint(1,100)  #tek bir değer döndürmek için kullanılır, son yazılan sayı/rakam dahil değildir

56

In [21]:
np.random.randint(1,20,8)

array([ 6, 10, 15,  7, 17,  1,  3, 15])

In [22]:
##herhangi bir diziyi bir değişkene eşitlemek için;

In [28]:
benimNumpyDizim = np.arange(1,50,8)

In [29]:
benimNumpyDizim

array([ 1,  9, 17, 25, 33, 41, 49])

In [30]:
benimRandomDizim = np.random.randint(1,20,8)

In [31]:
benimRandomDizim

array([ 2, 15, 16,  5,  7, 14, 16, 11])