## Numpy Dizi Methodları

In [1]:
import numpy as np

In [2]:
benimNpDizim = np.arange(20)

In [3]:
benimNpDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
benimNpDizim.reshape(4,5) #tek bir diziyi içerisinde bulunan değer sayısına göre başka dizilere bölmek için kullanılır

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
reshapeDizim = benimNpDizim.reshape(4,5)
reshapeDizim
reshapeDizim.shape  ##güncel olan dizinin kaça kaç bölündüğünü görmek için kullanılan bir özellik

(4, 5)

In [21]:
benimNpDizim.max()

19

In [6]:
benimNpDizim.min()

0

In [7]:
##random dizilerde max ve min sayının kaçıncı indexte olduğunu belirlemek için;

In [8]:
benimRandomDizim = np.random.randn(5)

In [9]:
benimRandomDizim

array([-0.21638148,  0.63587761, -0.34306176,  0.08284016,  0.04846995])

In [12]:
benimRandomDizim.max()

0.6358776057009983

In [13]:
benimRandomDizim.argmax()

1