In [1]:
import numpy as np

In [4]:
benimDizim = np.arange(0,17)

In [5]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [6]:
benimDizim[5]

5

In [8]:
benimDizim[3:9]

array([3, 4, 5, 6, 7, 8])

In [9]:
##dizide belirlenen aralıklarda ki değerlerin - değerler olarak değiştirilmesi sağlanabilir

In [10]:
benimDizim[3:8] = -5

In [11]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [12]:
baskaDizi = np.arange(0,24)

In [13]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
#bir dizideki belirlenen aralıklardaki değerleri başka bir diziye eşitledik
slicingDizisi = baskaDizi[4:9] 

In [26]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [27]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [28]:
#slicing dizisindeki bütün değerleri değiştirmek için;

In [29]:
slicingDizisi[:] = 700

In [47]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [30]:
##görüldüğü gibi slicingDizisi ndeki değerleri değiştirdiğimizde baskaDizi deki değelerde değişiyor
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [33]:
##değerlerin değişmesini istemiyorsak copy methodunu kullanmamız gerekir

In [34]:
ornekDizi = np.arange(0,24)

In [35]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [36]:
ornekDiziKopyası = ornekDizi.copy()

In [37]:
ornekDiziKopyası

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [38]:
ornekDiziKopyaSlicing = ornekDiziKopyası[3:6]

In [39]:
ornekDiziKopyaSlicing

array([3, 4, 5])

In [40]:
ornekDiziKopyaSlicing[:] = 800

In [41]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [45]:
ornekDiziKopyası #ornek dizinin kopyasını alarak bu kopyanın içinden seçtiğimiz bir aralığı yeni bir değişkene atadık
                 #değişiklikleri yeni değişkende yaparak asıl olan ornekDizi nin değişmesine engelledik
                 #ancak önceki notlarda olduğu gibi ornekDizi den kopyaladığımız ornekDiziKopyası ndaki değerler değişti

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [46]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])