## Matrix

In [1]:
import numpy as np

In [3]:
benimList = [[10,20,30], [20,30,40], [30,40,50]]

In [4]:
benimMatrixDizim = np.array(benimList)

In [5]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [7]:
benimMatrixDizim[0]

array([10, 20, 30])

In [10]:
benimMatrixDizim[0,2] veya benimMatrixDizim[1][2]

30

In [17]:
##slicing yapmak
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [11]:
benimMatrixDizim[0:2]

array([[10, 20, 30],
       [20, 30, 40]])

In [13]:
benimMatrixDizim[0:,2] #virgül kullanarak 0. indexten 2. indexe kadar gelip bu satırların 2. indexlerini seçmiş oluyoruz

array([30, 40, 50])

In [16]:
benimMatrixDizim[2:,2] #2. indexteki ve ondan sonraki değerleri getirip buradan 2. indexi seçmiş oluyoruz

array([50])

In [18]:
benimMatrixDizim[2:,1:] #2. indexteki ve ondan sonraki değerleri getirip buradan 1. index ve sonraki değerleri seçiyoruz

array([[40, 50]])