In [2]:
import numpy as np

In [3]:
yeniBirDizi = np.random.randint(1,100,20)

In [4]:
yeniBirDizi

array([84, 87, 98, 19, 73, 89, 43, 77, 89, 56, 86, 55, 16, 15, 40, 11, 92,
       38, 13, 12])

#

In [5]:
yeniBirDizi >24

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True, False,  True,  True,
       False, False])

In [6]:
sonucDizisi = yeniBirDizi > 24

In [7]:
sonucDizisi

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True, False,  True,  True,
       False, False])

In [8]:
yeniBirDizi[sonucDizisi]

array([84, 87, 98, 73, 89, 43, 77, 89, 56, 86, 55, 40, 92, 38])

#

In [11]:
sonDizi = np.arange(0,24)

In [12]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

#

In [14]:
np.sqrt(sonDizi)  ##karekök alma

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])